# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0bc8061cdc81ac1c375f51c7e91a2cec7fe57ad4ab5403b909fae44defb1b2047ace57613227df8fcc43ebd88c0496e17a088de63b1ca525f504dec3ef8786e

test:
  secret_key_base: 3140be51fe9ce121e16acee08f5df17d3263739773f479cd488df987556d544c6e5bcbf0d7411e57ec2c1d015df8d1fc2bfc25904ef89173e8bf4c12cbd3f215

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
